# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
print(X[0])

[619 'France' 0 42 2 0.0 1 1 1 101348.88]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
#to escape from onehotencoding trap
X=X[:,1:]

In [11]:
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [12]:
X[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [14]:
print(X)

[[-0.57873591 -0.57380915 -0.32622142 ...  0.64609167  0.97024255
   0.02188649]
 [-0.57873591  1.74273971 -0.44003595 ... -1.54776799  0.97024255
   0.21653375]
 [-0.57873591 -0.57380915 -1.53679418 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [-0.57873591 -0.57380915  0.60498839 ... -1.54776799  0.97024255
  -1.00864308]
 [ 1.72790383 -0.57380915  1.25683526 ...  0.64609167 -1.03067011
  -0.12523071]
 [-0.57873591 -0.57380915  1.46377078 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Building the ANN

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout


Using TensorFlow backend.


### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [18]:
#input dim 11 output dim 6
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [19]:
#with dropout to reduce overfitting
ann.add(tf.keras.layers.Dropout(rate=0.1))

### Adding the second hidden layer

In [20]:
#input dim 6 output dim 6
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
#with dropout to reduce overfitting
ann.add(tf.keras.layers.Dropout(rate=0.1))

### Adding the output layer

In [22]:
#input dim 6 output dim 1
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [24]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.5811 - accuracy: 0.7049
Epoch 2/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4910 - accuracy: 0.7945
Epoch 3/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4683 - accuracy: 0.7989
Epoch 4/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4545 - accuracy: 0.8031s - loss: 0.4551 - accuracy: 0.80
Epoch 5/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4461 - accuracy: 0.80 - 0s 30us/sample - loss: 0.4473 - accuracy: 0.8058
Epoch 6/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4434 - accuracy: 0.8087
Epoch 7/100
8000/8000 [==============================] - 0s 35us/sample - loss: 0.4397 - accuracy: 0.8125
Epoch 8/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.4342 - accuracy: 0.8126
Epoch 9/100
8000/8000 [==============================] 

## Making the predictions and evaluating the model

### Predicting the Test set results

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1545   50]
 [ 233  172]]


In [27]:
from sklearn.metrics import accuracy_score
# Model Accuracy, how often is the classifier correct?
print('Accuracy of Artificial Neural Network on test set: {:.2f}%'.format(accuracy_score(y_test, y_pred)*100))

Accuracy of Artificial Neural Network on test set: 85.85%


### Predicting a single new observation

In [28]:
# """
# Predict if the customer with the following informations will leave the bank or not:
# Geography: France
# Credit Score: 600
# Gender: Male
# Age: 40
# Tenure: 3
# Balance: 60000
# Number of Products: 2
# Has Credit Card: Yes
# Is Active Member: Yes
# Estimated Salary:50000
# """

In [29]:
#dataset to predict changed to categorical values
new_dataset=np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])
#dataset scaled
new_dataset=sc.transform(new_dataset)
new_dataset

array([[-0.57873591, -0.57380915, -0.52281016,  0.91241915,  0.10281024,
        -0.69598177, -0.26422114,  0.80773656,  0.64609167,  0.97024255,
        -0.87101922]])

In [30]:
new_prediction=ann.predict(new_dataset)
#to get ans in true or false
new_prediction=(new_prediction>0.5)

In [31]:
print(new_prediction[0,0])

False


# Alternative Approach- Evaluating the model

In [32]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

In [33]:
def build_classifier(optimizer='adam'):
    classifier = tf.keras.models.Sequential()
    classifier.add(tf.keras.layers.Dense(units=6, activation='relu'))
    classifier.add(tf.keras.layers.Dropout(rate=0.1))    
    classifier.add(tf.keras.layers.Dense(units=6, activation='relu'))
    classifier.add(tf.keras.layers.Dropout(rate=0.1))    
    classifier.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [34]:
#10 fold cross validation on dataset for better accuracy
classifier=KerasClassifier(build_fn=build_classifier, batch_size=10,nb_epoch=100)
accuracies=cross_val_score(estimator=classifier, X=X_train, y=y_train,cv=10,n_jobs=-1)

In [35]:
print(accuracies)

[0.78625    0.80000001 0.80124998 0.78125    0.81625003 0.81
 0.78750002 0.79374999 0.80124998 0.79500002]


In [36]:
mean=accuracies.mean()
print(mean)

0.7972500026226044


In [37]:
variance=accuracies.std()
print(variance)

0.010259144536026521


## Tuning the ANN

In [38]:
from sklearn.model_selection import GridSearchCV

In [39]:
classifier=KerasClassifier(build_fn=build_classifier)
parameters={'batch_size':[25,32],
           'nb_epoch':[100,500],
           'optimizer':['adam','rmsprop']}
grid_search=GridSearchCV(estimator=classifier,
                         param_grid=parameters,
                         scoring='accuracy',
                         cv=10)
grid_search=grid_search.fit(X_train,y_train)
best_parameters=grid_search.best_params_
best_Accuracy=grid_search.best_score_

Train on 7200 samples
7200/7200 [==============================] - 1s 114us/sample - loss: 0.5501 - accuracy: 0.7550
Train on 7200 samples
7200/7200 [==============================] - 1s 85us/sample - loss: 0.5998 - accuracy: 0.7001
Train on 7200 samples
7200/7200 [==============================] - 1s 104us/sample - loss: 0.6420 - accuracy: 0.6637
Train on 7200 samples
7200/7200 [==============================] - 1s 85us/sample - loss: 0.5600 - accuracy: 0.7349
Train on 7200 samples
7200/7200 [==============================] - 1s 142us/sample - loss: 0.5818 - accuracy: 0.7142
Train on 7200 samples
7200/7200 [==============================] - 1s 190us/sample - loss: 0.7110 - accuracy: 0.5876
Train on 7200 samples
7200/7200 [==============================] - 1s 108us/sample - loss: 0.6662 - accuracy: 0.6526
Train on 7200 samples
7200/7200 [==============================] - 1s 87us/sample - loss: 0.6376 - accuracy: 0.6800
Train on 7200 samples
7200/7200 [==============================] - 

In [40]:
print('Best Accuracy: {:.2f}%'.format(best_Accuracy*100))

Best Accuracy: 79.74%


In [41]:
print("Best Parameters:",best_parameters)

Best Parameters: {'batch_size': 32, 'nb_epoch': 100, 'optimizer': 'rmsprop'}


In [42]:
batch_size=best_parameters['batch_size']
nb_epoch=best_parameters['nb_epoch']
optimizer=best_parameters['optimizer']

In [43]:
#using the above parameters to fit the training dataset

tuned_classifier=KerasClassifier(build_fn=build_classifier, batch_size=batch_size,nb_epoch=nb_epoch,optimizer=optimizer)
tuned_classifier.fit(X_train, y_train)



Train on 8000 samples
8000/8000 [==============================] - 1s 86us/sample - loss: 0.6154 - accuracy: 0.7153


In [44]:
#run the tuned model on test dataset 
y_pred = tuned_classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [45]:
from sklearn.metrics import accuracy_score
# Model Accuracy, how often is the classifier correct?
print('Accuracy of Artificial Neural Network on test set: {:.2f}%'.format(accuracy_score(y_test, y_pred)*100))

Accuracy of Artificial Neural Network on test set: 79.80%


In [46]:
#predicting the likely of a customer to be associated with the bank

new_prediction=tuned_classifier.predict(new_dataset)
#to get ans in true or false
new_prediction=(new_prediction>0.5)
if(new_prediction[0,0]):
    print("Will Stay as a Customer with the Bank")
else:
    print("Will close the Account with the Bank")


Will close the Account with the Bank
